services:
  namenode:
    build:
      context: .
      dockerfile: nameNode/Dockerfile.namenode
    container_name: namenode
    ports:
      - "8000:8000"
    volumes:
      - namenode_data:/app/data
    restart: unless-stopped

  datanode1:
    build:
      context: .
      dockerfile: dataNode/Dockerfile.datanode
    container_name: datanode1
    environment:
      - DATANODE_PORT=50051
      - NAMENODE_URL=http://namenode:8000
      - DATANODE_NAME=datanode1
    ports:
      - "50051:50051"
    volumes:
      - datanode1_storage:/app/storage
    restart: unless-stopped
    depends_on:
      - namenode

  datanode2:
    build:
      context: .
      dockerfile: dataNode/Dockerfile.datanode
    container_name: datanode2
    environment:
      - DATANODE_PORT=50051
      - NAMENODE_URL=http://namenode:8000
      - DATANODE_NAME=datanode2
    ports:
      - "50052:50051"
    volumes:
      - datanode2_storage:/app/storage
    restart: unless-stopped
    depends_on:
      - namenode

  datanode3:
    build:
      context: .
      dockerfile: dataNode/Dockerfile.datanode
    container_name: datanode3
    environment:
      - DATANODE_PORT=50051
      - NAMENODE_URL=http://namenode:8000
      - DATANODE_NAME=datanode3
    ports:
      - "50053:50051"
    volumes:
      - datanode3_storage:/app/storage
    restart: unless-stopped
    depends_on:
      - namenode

volumes:
  namenode_data:
  datanode1_storage:
  datanode2_storage:
  datanode3_storage: