FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del NameNode
COPY nameNode/ /app/nameNode
COPY block_config.py /app/
COPY dataNode/protos /app/dataNode/protos
COPY nameNode/db.py /app/nameNode/

EXPOSE 8000
CMD ["uvicorn", "nameNode.main:app", "--host", "0.0.0.0", "--port", "8000"]
