# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dataNode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dataNode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61taNode.proto\x12\x08\x64\x61taNode\"\x1e\n\nDirRequest\x12\x10\n\x08\x64ir_name\x18\x01 \x01(\t\".\n\x0c\x42lockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"<\n\nBlockReply\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06status\x18\x03 \x01(\t2\xb4\x02\n\x0f\x44\x61taNodeService\x12:\n\nStoreBlock\x12\x16.dataNode.BlockRequest\x1a\x14.dataNode.BlockReply\x12\x38\n\x08GetBlock\x12\x16.dataNode.BlockRequest\x1a\x14.dataNode.BlockReply\x12;\n\x0b\x44\x65leteBlock\x12\x16.dataNode.BlockRequest\x1a\x14.dataNode.BlockReply\x12\x35\n\x07MakeDir\x12\x14.dataNode.DirRequest\x1a\x14.dataNode.BlockReply\x12\x37\n\tDeleteDir\x12\x14.dataNode.DirRequest\x1a\x14.dataNode.BlockReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataNode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIRREQUEST']._serialized_start=28
  _globals['_DIRREQUEST']._serialized_end=58
  _globals['_BLOCKREQUEST']._serialized_start=60
  _globals['_BLOCKREQUEST']._serialized_end=106
  _globals['_BLOCKREPLY']._serialized_start=108
  _globals['_BLOCKREPLY']._serialized_end=168
  _globals['_DATANODESERVICE']._serialized_start=171
  _globals['_DATANODESERVICE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
