# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dataNode_pb2 as dataNode__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dataNode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataNodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreBlock = channel.unary_unary(
                '/dataNode.DataNodeService/StoreBlock',
                request_serializer=dataNode__pb2.BlockRequest.SerializeToString,
                response_deserializer=dataNode__pb2.BlockReply.FromString,
                _registered_method=True)
        self.GetBlock = channel.unary_unary(
                '/dataNode.DataNodeService/GetBlock',
                request_serializer=dataNode__pb2.BlockRequest.SerializeToString,
                response_deserializer=dataNode__pb2.BlockReply.FromString,
                _registered_method=True)
        self.DeleteBlock = channel.unary_unary(
                '/dataNode.DataNodeService/DeleteBlock',
                request_serializer=dataNode__pb2.BlockRequest.SerializeToString,
                response_deserializer=dataNode__pb2.BlockReply.FromString,
                _registered_method=True)
        self.MakeDir = channel.unary_unary(
                '/dataNode.DataNodeService/MakeDir',
                request_serializer=dataNode__pb2.DirRequest.SerializeToString,
                response_deserializer=dataNode__pb2.BlockReply.FromString,
                _registered_method=True)
        self.DeleteDir = channel.unary_unary(
                '/dataNode.DataNodeService/DeleteDir',
                request_serializer=dataNode__pb2.DirRequest.SerializeToString,
                response_deserializer=dataNode__pb2.BlockReply.FromString,
                _registered_method=True)


class DataNodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataNodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreBlock,
                    request_deserializer=dataNode__pb2.BlockRequest.FromString,
                    response_serializer=dataNode__pb2.BlockReply.SerializeToString,
            ),
            'GetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=dataNode__pb2.BlockRequest.FromString,
                    response_serializer=dataNode__pb2.BlockReply.SerializeToString,
            ),
            'DeleteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBlock,
                    request_deserializer=dataNode__pb2.BlockRequest.FromString,
                    response_serializer=dataNode__pb2.BlockReply.SerializeToString,
            ),
            'MakeDir': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDir,
                    request_deserializer=dataNode__pb2.DirRequest.FromString,
                    response_serializer=dataNode__pb2.BlockReply.SerializeToString,
            ),
            'DeleteDir': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDir,
                    request_deserializer=dataNode__pb2.DirRequest.FromString,
                    response_serializer=dataNode__pb2.BlockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataNode.DataNodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataNode.DataNodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataNodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode.DataNodeService/StoreBlock',
            dataNode__pb2.BlockRequest.SerializeToString,
            dataNode__pb2.BlockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode.DataNodeService/GetBlock',
            dataNode__pb2.BlockRequest.SerializeToString,
            dataNode__pb2.BlockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode.DataNodeService/DeleteBlock',
            dataNode__pb2.BlockRequest.SerializeToString,
            dataNode__pb2.BlockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode.DataNodeService/MakeDir',
            dataNode__pb2.DirRequest.SerializeToString,
            dataNode__pb2.BlockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode.DataNodeService/DeleteDir',
            dataNode__pb2.DirRequest.SerializeToString,
            dataNode__pb2.BlockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
